export interface InitialCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  displayOrder: number;
}

export interface InitialPhoto {
  id: string;
  title: string;
  slug: string;
  description: string;
  imageUrl: string;
  imageAlt: string;
  categorySlug: string;
  location: string;
  shotAt: string;
  cameraSpecs: string;
  aspectRatio: string;
  published: boolean;
  displayOrder: number;
}

export const INITIAL_CATEGORIES: InitialCategory[] = [
  {
    id: "cat-portraits",
    name: "Portraits",
    slug: "portraits",
    description: "Studies in raw expression, cinematic lighting, and human vulnerability.",
    displayOrder: 1,
  },
  {
    id: "cat-architecture",
    name: "Architecture",
    slug: "architecture",
    description: "Monolithic concrete, light angles, and minimalist spatial structures.",
    displayOrder: 2,
  },
  {
    id: "cat-landscapes",
    name: "Landscapes",
    slug: "landscapes",
    description: "Sublime untamed terrains, quiet mornings, and Scandinavian mist.",
    displayOrder: 3,
  },
  {
    id: "cat-street",
    name: "Street",
    slug: "street",
    description: "Ephemeral geometry of metropolitan existence and candid nocturnal rhythms.",
    displayOrder: 4,
  },
  {
    id: "cat-editorial",
    name: "Editorial",
    slug: "editorial",
    description: "High-contrast fashion silhouettes, textile movement, and conceptual art.",
    displayOrder: 5,
  },
  {
    id: "cat-travel",
    name: "Travel & Sanctuaries",
    slug: "travel",
    description: "Visual essays on remote dwellings, temple shadows, and coastal solitude.",
    displayOrder: 6,
  },
];

export const INITIAL_PHOTOS: InitialPhoto[] = [
  {
    id: "photo-01",
    title: "Between Shadows & Solitude",
    slug: "between-shadows-and-solitude",
    description: "A study in natural window illumination and quiet contemplation within an 18th-century Parisian studio apartment. The contrast emphasizes texture and subtle skin tones.",
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Fine art editorial portrait bathed in warm natural side lighting",
    categorySlug: "portraits",
    location: "Paris, France",
    shotAt: "October 2025",
    cameraSpecs: "Leica M11 • Summilux-M 50mm f/1.4 ASPH • 1/250s f/2.0 ISO 100",
    aspectRatio: "4/5",
    published: true,
    displayOrder: 1,
  },
  {
    id: "photo-02",
    title: "Quiet Geometry in Concrete",
    slug: "quiet-geometry-in-concrete",
    description: "Brutalist architectural lines slicing through overcast Scandinavian skies. The interplay of diagonal shadows creates a rhythm of monumental calmness.",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Minimalist brutalist concrete architecture with sharp light and shadows",
    categorySlug: "architecture",
    location: "Copenhagen, Denmark",
    shotAt: "August 2025",
    cameraSpecs: "Hasselblad 907X 50C • XCD 45mm f/4 P • 1/500s f/8.0 ISO 64",
    aspectRatio: "16/10",
    published: true,
    displayOrder: 2,
  },
  {
    id: "photo-03",
    title: "The Nordic Horizon",
    slug: "the-nordic-horizon",
    description: "Subtle mist drifting across the black sand coastline of Vik at first dawn. The monochrome palette of volcanic basalt and churning ocean creates an ethereal atmosphere.",
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Atmospheric misty mountains and pristine reflective water at sunrise",
    categorySlug: "landscapes",
    location: "Vik, Iceland",
    shotAt: "September 2025",
    cameraSpecs: "Sony A7R V • FE 24-70mm f/2.8 GM II • 1/125s f/11 ISO 100",
    aspectRatio: "16/10",
    published: true,
    displayOrder: 3,
  },
  {
    id: "photo-04",
    title: "Nocturne in Shinjuku",
    slug: "nocturne-in-shinjuku",
    description: "Neon reflections dancing on rain-slicked asphalt amidst the dense alleyways of Tokyo. A lone commuter with an umbrella creates a cinematic narrative moment.",
    imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Atmospheric rainy Tokyo street scene illuminated by warm golden lanterns",
    categorySlug: "street",
    location: "Tokyo, Japan",
    shotAt: "November 2025",
    cameraSpecs: "Fujifilm GFX 100S • GF 63mm f/2.8 R WR • 1/60s f/2.8 ISO 800",
    aspectRatio: "4/5",
    published: true,
    displayOrder: 4,
  },
  {
    id: "photo-05",
    title: "Silk & Shadow",
    slug: "silk-and-shadow",
    description: "Commissioned fashion editorial exploring tension between fluid linen drapes and sharp studio chiaroscuro. The sculptural pose mimics classical Grecian marble.",
    imageUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "High fashion editorial portrait featuring structured flowing linen silhouette",
    categorySlug: "editorial",
    location: "Milan, Italy",
    shotAt: "January 2026",
    cameraSpecs: "Leica SL2 • APO-Summicron-SL 75mm f/2 ASPH • 1/160s f/4.0 ISO 50",
    aspectRatio: "4/5",
    published: true,
    displayOrder: 5,
  },
  {
    id: "photo-06",
    title: "Kyoto Temple Pavilion",
    slug: "kyoto-temple-pavilion",
    description: "Golden hour filtering through cedar lattice screens inside a centuries-old Zen monastery. The balance between ancient craftsmanship and natural serenity.",
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Traditional Japanese wooden temple garden bathed in late afternoon light",
    categorySlug: "travel",
    location: "Kyoto, Japan",
    shotAt: "November 2025",
    cameraSpecs: "Leica M11 • Elmarit-M 28mm f/2.8 ASPH • 1/320s f/5.6 ISO 200",
    aspectRatio: "16/10",
    published: true,
    displayOrder: 6,
  },
  {
    id: "photo-07",
    title: "Gaze of the Sculptor",
    slug: "gaze-of-the-sculptor",
    description: "An intimate character portrait of master ceramicist Julien Fontaine in his Belleville studio. Raw clay remnants on hands and an intense, meditative focus.",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Expressive black and white monochrome portrait of an artist in studio",
    categorySlug: "portraits",
    location: "Paris, France",
    shotAt: "December 2025",
    cameraSpecs: "Leica M11 Monochrom • Summilux-M 35mm f/1.4 ASPH • 1/180s f/2.0 ISO 400",
    aspectRatio: "4/5",
    published: true,
    displayOrder: 7,
  },
  {
    id: "photo-08",
    title: "The Spiral of Light",
    slug: "the-spiral-of-light",
    description: "Looking up through the continuous spiral staircase of the Vatican Museums. An homage to Fibonacci proportions and architectural fluidity.",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Dramatic spiral staircase looking upward with geometric symmetry",
    categorySlug: "architecture",
    location: "Rome, Italy",
    shotAt: "July 2025",
    cameraSpecs: "Sony A7R V • FE 16-35mm f/2.8 GM II • 1/60s f/8.0 ISO 160",
    aspectRatio: "4/5",
    published: true,
    displayOrder: 8,
  },
  {
    id: "photo-09",
    title: "Dolomite Solitude",
    slug: "dolomite-solitude",
    description: "Jagged limestone peaks of Tre Cime di Lavaredo breaking through morning cloud inversions at 2,400 meters altitude. Silent grandeur before the sun crests.",
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Towering mountain peaks bathed in golden alpine sunrise glow",
    categorySlug: "landscapes",
    location: "Dolomites, Italy",
    shotAt: "June 2025",
    cameraSpecs: "Hasselblad 907X 50C • XCD 90mm f/3.2 • 1/200s f/8.0 ISO 100",
    aspectRatio: "16/10",
    published: true,
    displayOrder: 9,
  },
  {
    id: "photo-10",
    title: "Passing Shadows in Soho",
    slug: "passing-shadows-in-soho",
    description: "Late afternoon high-contrast shadows casting elongated silhouettes along historic cast-iron facades in Lower Manhattan. Fleeting urban solitude.",
    imageUrl: "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Urban cityscape with golden late afternoon sun hitting modern architecture",
    categorySlug: "street",
    location: "New York City, USA",
    shotAt: "May 2025",
    cameraSpecs: "Leica Q3 • Summilux 28mm f/1.7 ASPH • 1/1000s f/5.6 ISO 125",
    aspectRatio: "16/10",
    published: true,
    displayOrder: 10,
  },
  {
    id: "photo-11",
    title: "Velvet Reverie",
    slug: "velvet-reverie",
    description: "Editorial series for Maison L’Ombre featuring deep emerald velvet textiles draped against raw limestone walls. Minimalist beauty in stillness.",
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Fashion model in elegant designer ensemble with soft ambient studio lighting",
    categorySlug: "editorial",
    location: "Antwerp, Belgium",
    shotAt: "February 2026",
    cameraSpecs: "Fujifilm GFX 100 II • GF 110mm f/2 R LM WR • 1/160s f/2.8 ISO 100",
    aspectRatio: "4/5",
    published: true,
    displayOrder: 11,
  },
  {
    id: "photo-12",
    title: "The Berber Oasis",
    slug: "the-berber-oasis",
    description: "Earthen adobe architecture emerging from the edge of the Erg Chebbi dunes at sunset. The terracotta tones blend seamlessly with the shifting sand ridges.",
    imageUrl: "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Desert sand dunes casting graceful warm ripples under evening sunset",
    categorySlug: "travel",
    location: "Merzouga, Morocco",
    shotAt: "April 2025",
    cameraSpecs: "Leica M11 • Summicron-M 35mm f/2 ASPH • 1/400s f/4.0 ISO 100",
    aspectRatio: "16/10",
    published: true,
    displayOrder: 12,
  },
  {
    id: "photo-13",
    title: "Elegance of the Void",
    slug: "elegance-of-the-void",
    description: "Minimalist geometric abstraction of the MAXXI Museum designed by Zaha Hadid. The pure curved white concrete ribbons intersect effortlessly against deep blue skies.",
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Futuristic curved modern architecture reflecting brilliant morning sky",
    categorySlug: "architecture",
    location: "Rome, Italy",
    shotAt: "July 2025",
    cameraSpecs: "Sony A7R V • FE 24-70mm f/2.8 GM II • 1/800s f/8.0 ISO 100",
    aspectRatio: "4/5",
    published: true,
    displayOrder: 13,
  },
  {
    id: "photo-14",
    title: "Gaze Across the Seine",
    slug: "gaze-across-the-seine",
    description: "Early morning autumn mist hovering over Pont Neuf. A contemplative profile captured during the first soft golden rays touching the historic riverbanks.",
    imageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Natural portrait with gentle sunlight catching facial features against soft bokeh",
    categorySlug: "portraits",
    location: "Paris, France",
    shotAt: "November 2025",
    cameraSpecs: "Leica M11 • Noctilux-M 50mm f/0.95 ASPH • 1/1000s f/1.2 ISO 64",
    aspectRatio: "4/5",
    published: true,
    displayOrder: 14,
  },
  {
    id: "photo-15",
    title: "Submerged Twilight",
    slug: "submerged-twilight",
    description: "Mirror reflections on Lake Braies at blue hour after the autumn crowds have departed. Perfect glassy stillness broken only by a lone wooden rowboat.",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Pristine alpine lake reflections with distant mountain ranges at twilight",
    categorySlug: "landscapes",
    location: "Lago di Braies, Italy",
    shotAt: "October 2025",
    cameraSpecs: "Hasselblad 907X 50C • XCD 30mm f/3.5 • 2.5s f/11 ISO 100",
    aspectRatio: "16/10",
    published: true,
    displayOrder: 15,
  },
  {
    id: "photo-16",
    title: "Shadows in the Medina",
    slug: "shadows-in-the-medina",
    description: "Geometric cedar slats filtering narrow slits of desert sun across the earthen stone passageways of Fes el Bali. Time appears suspended.",
    imageUrl: "https://images.unsplash.com/photo-1539635278303-d4002c07eae3?q=80&w=1600&auto=format&fit=crop",
    imageAlt: "Atmospheric street photography inside ancient Medina alleys with dramatic sunlight",
    categorySlug: "travel",
    location: "Fes, Morocco",
    shotAt: "April 2025",
    cameraSpecs: "Leica Q3 • 28mm f/1.7 • 1/500s f/4.0 ISO 200",
    aspectRatio: "4/5",
    published: true,
    displayOrder: 16,
  },
];
